---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - variables.yml
  tasks:

    - name: Collect Ext1_PG Network id
      command: sudo pwsh ./Ext1_PG_key.ps1
      register: Ext1_PG_key

    - debug: var=Ext1_PG_key

    - name: Collect Ext2_PG Network id
      command: sudo pwsh ./Ext2_PG_key.ps1
      register: Ext2_PG_key

    - name: Collect Transport_PG Network id
      command: sudo pwsh ./Transport_PG_key.ps1
      register: Transport_PG_key

    - name: Collect Compute Manager id for "{{vc_hostname}}"
      nsxt_fabric_compute_managers_facts:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
      register: vc

    - name: Add Third Edge VM
      nsxt_fabric_nodes:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
        resource_type: "EdgeNode"
        display_name: "{{edge3_name}}"
        ip_addresses:
          - "{{edge3_mgmt_ip}}"
        deployment_config:
          form_factor: "{{edge3_size}}"
          node_user_settings:
            cli_password: "{{edge3_password}}"
            root_password: "{{edge3_password}}"
          vm_deployment_config:
            placement_type: VsphereDeploymentConfig
            vc_id: "{{vc.results[0].id}}"
            data_network_ids:
            - "{{Ext1_PG_key.stdout}}"
            - "{{Ext2_PG_key.stdout}}"
            - "{{Transport_PG_key.stdout}}"
            management_network_id: "dvportgroup-263"
            hostname: "{{edge3_name}}"
            compute_id: "domain-c26"
            storage_id: "datastore-201"
            default_gateway_addresses:
            - "{{edge3_mgmt_ip_gw}}"
            management_port_subnets:
            - ip_addresses:
              - "{{edge3_mgmt_ip}}"
              prefix_length: "{{edge3_mgmt_ip_mask}}"
        state: present

    - name: Add Fourth Edge VM
      nsxt_fabric_nodes:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
        resource_type: "EdgeNode"
        display_name: "{{edge4_name}}"
        ip_addresses:
          - "{{edge4_mgmt_ip}}"
        deployment_config:
          form_factor: "{{edge4_size}}"
          node_user_settings:
            cli_password: "{{edge4_password}}"
            root_password: "{{edge4_password}}"
          vm_deployment_config:
            placement_type: VsphereDeploymentConfig
            vc_id: "{{vc.results[0].id}}"
            data_network_ids:
            - "{{Ext1_PG_key.stdout}}"
            - "{{Ext2_PG_key.stdout}}"
            - "{{Transport_PG_key.stdout}}"
            management_network_id: "dvportgroup-263"
            hostname: "{{edge4_name}}"
            compute_id: "domain-c26"
            storage_id: "datastore-202"
            default_gateway_addresses:
            - "{{edge4_mgmt_ip_gw}}"
            management_port_subnets:
            - ip_addresses:
              - "{{edge4_mgmt_ip}}"
              prefix_length: "{{edge4_mgmt_ip_mask}}"
        state: present

    - name: Remove Edge VMs Memory reservation
      command: pwsh ./remove_edge_reservations.ps1

    - name: Create uplink profile for edge nodes
      nsxt_uplink_profiles:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{item.display_name}}"
        mtu: 1700
        teaming: "{{item.teaming}}"
        transport_vlan: "{{item.transport_vlan}}"
        state: "present"
      with_items:
        - "{{uplink_profiles_edges}}"

    - name: Create edge transport nodes
      nsxt_transport_nodes:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
        resource_type: TransportNode
        display_name: "{{item.display_name}}"
        description: NSX Edge Transport Node
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        transport_zone_endpoints: "{{item.transport_zone_endpoints}}"
        fabric_node_name: "{{item.fabric_node_name}}"
        state: present
      with_items:
        - "{{edges_transport_nodes}}"

    - name: Add edge cluster "{{edge_cluster_name}}"
      nsxt_edge_clusters:
        hostname: "{{nsx_hostname}}"
        username: "{{nsx_username}}"
        password: "{{nsx_password}}"
        validate_certs: False
        display_name: "{{edge_cluster_name}}"
        members:
        - transport_node_name: "Edge03"
        - transport_node_name: "Edge04"
        state: present

